### PR TITLE
Adding a picture from Github for a user

### PR DESCRIPTION
**Pull request by MichaelSefranek**
When a user logs in, they will be able to see their user profile from Github.  This will use the Github API, and the.
- [x] get one image from a static Github profile to appear somewhere on the page, when a user logs in.
- [x] store the relative API information as part of the student class

### CODE REVIEW

**Comment by MichaelSefranek** [comment]
So ultimately the Github API is returning a large amount of HTML when we call a command like ` mal = github.repos.list user: 'malastrumdominisui'`  And I can see the thing that I want which is basically: `<Hashie::Mash avatar_url="https://avatars1.githubusercontent.com/u/24572807?v=3" ` And this is contained within the Github::ResponseWrapper .

**Comment by MichaelSefranek** [comment]
The final expression I figured out is to do this: 
```
git_thing = Github.new
user_dump = mal.repos.list user: 'malastrumdominisui'
user_dump.body[0]["owner"]["avatar_url"]
```

**Comment by MichaelSefranek** [comment]
So this is my standoff, just chasing a rabbit, for now.  
The good news is  now we can easily capture a git image.  If you simply go to https://github.com/<username>.png it forwards you to the image.

I have put my username as a placeholder in the JS timing.js file where we generate all the posts from an array.  From there we go to the rabbit hole, and I am a bit frustrated at looking at it for now.  I'll come back to it.

timing.js -> /display -> Posts class 
Posts object is created only when we /getinfo, which is really only on the admin side, querying the data
so the real answer is to change what Posts are is when we submit them (in submissions)

so rubber ducking a bit here, and I will drop this tonight.  I want to basically add one more `param` to `Submission.create` when we take a submission in the `/submit` controller action.  To do this I will add one more form in the /submit form in the header, right next to name.  I will accept that, and add it to our database (and add a new column to the students database.)  This will be funneled in the exact same way we create a name, so that we only refer to it once.

As a future note, it will be better to probably map the "submitting" of student name and git username to a seperate login action, rather than submit the name every time.  

So a future "story" may be:
When a goes to the page for the first time, they will be prompted to sign up.  They will enter a name, username, password, and git_name.  Then they will see their name appear above the "what are you working on" box, as long as they are logged in.

this would take the place of our dummy sessions variable in place right now.

**Comment by MichaelSefranek** [comment]
before testing this you have to add a column manually to your students table called git.  You also have to hard code github user names into that column.

Now when we erb /display, a `Posts` object will now contain the value of the git username.  It uses this in  `Posts.front_page_json` to send the git username to the front page where we display it.

**Review by jlocatis — COMMENTED** [review]
All pushed together.

**Review by jlocatis — APPROVED** [review]
Looks good.

**Pull request merged**
