### PR TITLE
Referencing the name to the new names table.

### PR DESCRIPTION
**Pull request by MichaelSefranek**
My goal here is that wherever a name appears on our project, that name is an actual reference to the name from the names table.  At this point I am not sure if this should all be done on the Ruby side, or if there is some convenient SQL feature to combine tables within the database itself.

### CODE REVIEW

**Comment by MalastrumDominiSui** [comment]
so 
```
    new_submission = "'#{Time.now.strftime("%x")}','#{Time.now.to_i}','#{student.last_submission_at}','#{params[:name]}',#{params[:stressLevel]},'#{submission}'"
```
is the line where we create a string preformmated for SQL to recieve it, this is where I need to replace `'#{params[:name]}' ` with our foreign key ID from the names table

**Comment by MichaelSefranek** [comment]
Now the key is being captured via the getKey function in the students class. My next task is to take that key, while we are in Submission.create, and make sure our Submission, which is sent to the Submissions table is receiving our unique id, our foreign key from the names table.

**Comment by MichaelSefranek** [comment]
Replacing all instances where name appeared and is used on the backend is proving to be a little expansive.  I'll everything I can think of and double check.
- [ ] Need to delete names column from submissions table
- [ ] In submissions, eliminate instances of 'name' reference and replace with a student's key
- [ ] in last_submission in the student class, name is referenced from the submissions table
- [ ] in posts, get requested posts by name references name from submissions table
- [ ] remember to fix javascript timing function before merging
- if I get all of these, I am not sure but it should take care of the front end.

**Comment by MichaelSefranek** [comment]
I think I must be doing this wrong.  I feel like there is something easy in SQL i need to do rather than what I have been wasting my time on.

**Pull request merged**
