### PR TITLE
Refactoring Posts

### PR DESCRIPTION
**Pull request by sumeetjain**
Starting from 'master' anew to consolidate functions related to posts.

### CODE REVIEW

**Comment by sumeetjain** [comment]
First, we're going to move some DB calls in the controller out to the model layer.

```ruby
get "/display" do
  @dailyPosts = $database.posts_today

  # TODO Move all DB functionality into a model/service, e.g.:
  # @dailyPosts = Post.today
  
  @dailyPosts.to_json
end
```

**Comment by sumeetjain** [comment]
Next, we're going to pull the Database class's `posts_today` method out of that class; since that method is too specific about DB content. It either doesn't belong in the Database class, or it should be designed/named more generically so it's not specifically about "posts" or "today".

**Comment by sumeetjain** [comment]
Nice Mike! What's next?

**Comment by MichaelSefranek** [comment]
Well the interior of the function looks like this 

```ruby
CSV.foreach('./public/database.csv', {headers:true}) do |row|
  rowEpoch = Time.at(row["time"].to_i)
  if rowEpoch.yday == todaysYearDay
    postCollection.push([row["name"],rowEpoch.strftime("%m/%d @ %I:%M%p"), row["submission"]])
  end
end
```

which relies on the CSV, and this really seems like a responsibility of the Database class, so I am thinking it should be looking towards the Database.

**Comment by MichaelSefranek** [comment]
Now I understand: I need to use the all_filtered function, with a specific Proc (and do this within the posts class).  The filter will tell me whether time in the "time" converted to year day is equal to todays day.

**Comment by MichaelSefranek** [comment]
Now I have an error when I displayed I recognize a pattern, I know it is in the Javascript "timing" file, and it has something to do with the indices calling on strings instead of array indices.  Attempting to fix.

**Comment by MichaelSefranek** [comment]
I need to try and get the response from /display to return an array of array of strings, instead of an array of strings, which is harder to parse.

**Comment by sumeetjain** [comment]
Great work so far, Mike. Here are your next steps (once you fix the JavaScript issue).

First, there is this TODO at the top of the Posts model:

> Refactor this entire class to not be limited to only getting collections of posts for a specific user and date. Let it be a more generic PostCollection creator.

I would like to _not_ actually fix that TODO. Let's keep the Posts model exactly as it is, which is described in that model as:

```
# This class is for functionality related to ALL of a student's posts for a
# particular day. That is, one object/instance of this class is ALL of a 
# student's posts for one day.
```

So the `Posts` class is **only** for collections of posts filtered by **both** a student's name and a particular day.

That means that your method, `Posts.today` **should go elsewhere**. I'd like you to move that method to the `Post` (singular!) model. This should be a pretty minor change. The method should still be a class method (not an instance method) in the `Post` model.

---

Once that's done...

Have a teammate review this PR, and then with them merge it into 'master'.

Then your next task, **in a new branch and new PR:**

Write a test for the `Post.today` (not `Posts.today`, since that doesn't exist anymore!) in **spec/models/post_spec.rb**.

Use your new PR to have a conversation with yourself about how that's going, and remember 'Red, Green, Refactor'.

**Comment by MichaelSefranek** [comment]
Javascript is receiving the response from /display in the proper format, but that date is not formatted correctly for display.  Date is in Epoch, and needs to be 00/00/0000 format.

**Comment by MichaelSefranek** [comment]
got Post moved- I had not realized the file wasn't added to main.  Thanks to Jaime for spotting it.  Next I will look at formatting that wrong Javascript time, so I can push to Master.

**Comment by MichaelSefranek** [comment]
Got the time working,  I am not sure how to reconcile what I just did with what Jaime and Ben have done, since their Post class works fine, and mine is probably overlapping with theirs.

**Comment by MichaelSefranek** [comment]
looking at admin functionality with the new stuff, since we lost it

**Comment by MichaelSefranek** [comment]
get_posts_by_date in posts class is displaying on the /admin page via the response from /getinfo in the controller action.  I am looking instead at modifying our new Post.today function in the Post class to accept any day.  I think this could replace get_posts_by_date.  I am not sure what instance variables Post should have yet, even though it has a class method.

**Review by jlocatis — APPROVED** [review]
Merged with master.

**Pull request merged**
